GET http://localhost:3333/products

###
GET http://localhost:3333/products/4

###
DELETE http://localhost:3333/products/4

###
POST http://localhost:3333/products
content-type: application/json

{
    "name": "Alo vc",
    "price": 123
}

###
PATCH  http://localhost:3333/products/5
content-type: application/json

{
    "name": "Updated",
    "price": 589
}